global:
  clusterIdentity: postgresk4ldcb
gateway:
  enabled: true
postgresql:
  enabled: true
  externalAccess:
    enabled: true
    publicHostnames:
    - seang-clone.seang.shop
  tls:
    enabled: true
    mode: operator
  cluster:
    imageName: ghcr.io/cloudnative-pg/postgresql:16.2
    instances: 3
    bootstrap:
      database: database
      owner: app_seang
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi
  storage:
    size: 3Gi
  pooler:
    enabled: true
  externalSecretRef: postgresk4ldcb-postgresql-app
  superuserExternalSecretRef: postgresk4ldcb-postgresql-credentials
