global:
  clusterIdentity: project-seang
gateway:
  enabled: true
postgresql:
  enabled: true
  externalAccess:
    enabled: true
    publicHostnames:
    - project-seang.seang.shop
  tls:
    enabled: true
    mode: operator
  cluster:
    bootstrap:
      database: database
      owner: app_project_seang
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1Gi
  storage:
    size: 5Gi
  pooler:
    enabled: true
  externalSecretRef: project-seang-postgresql-app
  superuserExternalSecretRef: project-seang-postgresql-credentials
