global:
  clusterIdentity: aweg-b5b507c8
externalTcpProxy:
  expose:
    postgresql: true
    mongodb: false
    mysql: false
    redis: false
    cassandra: false
  ports:
    postgresql: 15437
postgresql:
  enabled: true
  externalAccess:
    enabled: true
    publicHostnames:
    - aweg.seang.shop
  tls:
    enabled: true
    mode: operator
  cluster:
    bootstrap:
      database: aweg
      owner: app_aweg
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1Gi
  storage:
    size: 10Gi
  credentials:
    admin: aege
    superuser: aege
