global:
  clusterIdentity: test-0e8fe76c
  vault:
    enabled: false
  externalSecrets:
    enabled: false
gateway:
  enabled: true
externalTcpProxy:
  enabled: false
  expose:
    postgresql: true
    mongodb: false
    mysql: false
    redis: false
    cassandra: false
  ports:
    postgresql: 15433
postgresql:
  enabled: true
  externalAccess:
    enabled: true
    publicHostnames:
    - test.seang.shop
  tls:
    enabled: true
    mode: operator
  cluster:
    bootstrap:
      database: jeof
      owner: eijo
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1Gi
  storage:
    size: 10Gi
  credentials:
    superuser: efwr
    admin: efwr
