global:
  clusterIdentity: postgresl17h0w
gateway:
  enabled: true
postgresql:
  enabled: true
  externalAccess:
    enabled: true
    publicHostnames:
    - seang-clone.seang.shop
  tls:
    enabled: true
    mode: operator
  cluster:
    imageName: ghcr.io/cloudnative-pg/postgresql:16.2
    bootstrap:
      database: seang
      owner: app_seang
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1Gi
  storage:
    size: 5Gi
  pooler:
    enabled: true
  externalSecretRef: postgresl17h0w-postgresql-app
  superuserExternalSecretRef: postgresl17h0w-postgresql-credentials
