global:
  clusterIdentity: seang-mongo-b96c5a9c
externalTcpProxy:
  ports:
    mongodb: 17017
mongodb:
  enabled: true
  externalAccess:
    enabled: true
    publicHostnames:
    - mongo-db-0.seang.shop
    - mongo-db-1.seang.shop
    - mongo-db-2.seang.shop
    replicaSetHorizons:
      enabled: true
      basePort: 17017
  tls:
    enabled: true
    mode: certManager
  connection:
    username: mongodb
    password: mongodb@0405
    port: 17017
  clusterServiceDNSSuffix: cluster2
  backup:
    enabled: true
    task:
      schedule: 10 2 * * *
