global:
  clusterIdentity: leang
gateway:
  enabled: true
postgresql:
  enabled: true
  externalAccess:
    enabled: true
    publicHostnames:
    - leang.seang.shop
  tls:
    enabled: true
    mode: operator
  cluster:
    imageName: ghcr.io/cloudnative-pg/postgresql:17
    instances: 2
    bootstrap:
      database: database
      owner: app_leang
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi
  storage:
    size: 4Gi
  pooler:
    enabled: true
  externalSecretRef: leang-postgresql-app
  superuserExternalSecretRef: leang-postgresql-credentials
