global:
  clusterIdentity: aweg-051ca9e0
  vault:
    enabled: false
  externalSecrets:
    enabled: false
gateway:
  enabled: true
externalTcpProxy:
  enabled: false
postgresql:
  enabled: true
  externalAccess:
    enabled: true
    publicHostnames:
    - aweg.seang.shop
  tls:
    enabled: true
    mode: operator
  cluster:
    bootstrap:
      database: avea
      owner: app_aweg
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1Gi
  storage:
    size: 10Gi
  credentials:
    superuser: aegae
    admin: aegae
