global:
  clusterIdentity: seang-mysql-97fa7841
externalTcpProxy:
  ports:
    mysql: 13306
mysql:
  enabled: true
  externalAccess:
    enabled: true
    publicHostnames:
    - mysql-db.seang.shop
  tls:
    enabled: true
    mode: certManager
  connection:
    username: mysql
    password: mysql@1234
    port: 13306
  haproxy:
    size: 2
  backup:
    enabled: true
    schedule:
      cron: 20 2 * * *
