global:
  clusterIdentity: ka
gateway:
  enabled: true
postgresql:
  enabled: true
  externalAccess:
    publicHostnames:
    - ka.seang.shop
  cluster:
    instances: 3
    bootstrap:
      database: kaka
      owner: app_ka
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi
  storage:
    size: 4Gi
    wal:
      enabled: false
  pooler:
    enabled: true
  externalSecretRef: ka-postgresql-app
  superuserExternalSecretRef: ka-postgresql-credentials
