global:
  clusterIdentity: postgres
gateway:
  enabled: true
postgresql:
  enabled: true
  externalAccess:
    enabled: true
    publicHostnames:
    - postgres-db.seang
  tls:
    enabled: true
    mode: operator
  cluster:
    bootstrap:
      database: appdb
      owner: app_postgres
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1Gi
  storage:
    size: 10Gi
  externalSecretRef: postgres-postgresql-app
  superuserExternalSecretRef: postgres-postgresql-credentials
