global:
  clusterIdentity: seang-mysql-2258e80e
mysql:
  enabled: true
  externalAccess:
    enabled: true
    publicHostnames:
    - mysql-db.seang.shop
  haproxy:
    size: 2
  credentials:
    monitorPassword: MysqlStrongPassword123!
    rootPassword: MysqlStrongPassword123!
    clusterCheckPassword: MysqlStrongPassword123!
    replicationPassword: MysqlStrongPassword123!
  backup:
    enabled: true
    schedule:
      cron: 20 2 * * *
