global:
  clusterIdentity: seang-redis-c93ca6c2
redis:
  enabled: true
  externalAccess:
    enabled: true
    publicHostnames:
    - redis-db.seang.shop
  tls:
    enabled: true
    mode: certManager
  exporter:
    enabled: true
  auth:
    password: RedisStrongPassword123!
