global:
  clusterIdentity: ma
  backupBucket: a8s-clusterdb-backup
gateway:
  enabled: true
postgresql:
  enabled: true
  externalAccess:
    publicHostnames:
    - ma.autonomous-istad.com
  cluster:
    imageName: ghcr.io/cloudnative-pg/postgresql:18.4
    instances: 3
    bootstrap:
      database: ma
      owner: ma
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi
  storage:
    size: 4Gi
    wal:
      enabled: false
  pooler:
    enabled: true
  externalSecretRef: ma-postgresql-app
  superuserExternalSecretRef: ma-postgresql-credentials
