global:
  clusterIdentity: seang-mongo-85e71f65
externalTcpProxy:
  ports:
    mongodb: 17017
mongodb:
  enabled: true
  externalAccess:
    enabled: true
    publicHostnames:
    - mongo-db-0.seang.shop
    - mongo-db-1.seang.shop
    - mongo-db-2.seang.shop
    replicaSetHorizons:
      enabled: true
      basePort: 17017
  tls:
    enabled: true
    mode: certManager
  connection:
    username: postgres
    password: postgres@1234
    port: 17017
  backup:
    enabled: true
    task:
      schedule: '* 9 * * *'
      timeZone: Asia/Phnom_Penh
