global:
  clusterIdentity: kean
gateway:
  enabled: true
redis:
  enabled: true
  externalAccess:
    enabled: true
    publicHostnames:
    - kean-redis-leader-0.seang.shop
    - kean-redis-leader-1.seang.shop
    redisClusterDomainSuffix: seang.shop
  tls:
    enabled: true
    mode: certManager
  storage:
    size: 3Gi
  exporter:
    enabled: true
  cluster:
    image: redis:8.0-alpine
    instances: 2
    leaderReplicas: 2
    followerReplicas: 0
    bootstrapSlots:
      enabled: true
    resources:
      requests:
        cpu: 75m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 512Mi
  externalSecretRef: kean-redis-credentials
