global:
  clusterIdentity: adf-f69f880c
externalTcpProxy:
  ports:
    postgresql: 5432
postgresql:
  enabled: true
  cluster:
    bootstrap:
      database: asdf
      owner: app_adf
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1Gi
  storage:
    size: 10Gi
  credentials:
    admin: asdf
    superuser: asdf
