apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: abc-tcp
  namespace: ns-a8s-admin-c36fc7af
spec:
  entryPoints:
  - postgresql
  routes:
  - match: HostSNI(`abc.seang.shop`)
    services:
    - name: abc-postgresql-pooler-rw
      port: 5432
  tls:
    passthrough: true
