global:
  clusterIdentity: mydbcluster
  backupBucket: a8s-clusterdb-backup
gateway:
  enabled: true
postgresql:
  enabled: true
  externalAccess:
    enabled: true
    publicHostnames:
    - mydbcluster.autonomous-istad.com
  tls:
    enabled: true
    mode: operator
  cluster:
    imageName: ghcr.io/cloudnative-pg/postgresql:18.4
    bootstrap:
      database: mydb
      owner: app_mydbcluster
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi
  storage:
    size: 4Gi
  pooler:
    enabled: true
  externalSecretRef: mydbcluster-postgresql-app
  superuserExternalSecretRef: mydbcluster-postgresql-credentials
