externalTcpProxy:
  ports:
    mongodb: 17017
mongodb:
  externalAccess:
    enabled: true
    publicHostnames:
    - mongo-db-0.seang.shop
    - mongo-db-1.seang.shop
    - mongo-db-2.seang.shop
    replicaSetHorizons:
      enabled: true
      basePort: 27017
  enabled: true
  clusterServiceDNSSuffix: k8scluster
  cluster: {
    }
  credentials:
    backupPassword: MongoStrongPassword123!
    clusterAdminPassword: MongoStrongPassword123!
    replicationKey: MongoStrongPassword123!
    userAdminPassword: MongoStrongPassword123!
    databaseAdminPassword: MongoStrongPassword123!
    clusterMonitorPassword: MongoStrongPassword123!
  backup:
    enabled: true
    task:
      schedule: 10 2 * * *
    s3:
      bucket: ns-seang-03
      prefix: db-seang-mongo/db-seang-mongo-mongodb
