global:
  clusterIdentity: postgres3vphiu
  backupBucket: a8s-clusterdb-backup
gateway:
  enabled: true
postgresql:
  enabled: true
  externalAccess:
    enabled: true
    publicHostnames:
    - seang-clone.autonomous-istad.com
  tls:
    enabled: true
    mode: operator
  cluster:
    imageName: ghcr.io/cloudnative-pg/postgresql:16.14
    instances: 3
    bootstrap:
      database: database
      owner: app_seang
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi
  storage:
    size: 4Gi
  pooler:
    enabled: true
  externalSecretRef: postgres3vphiu-postgresql-app
  superuserExternalSecretRef: postgres3vphiu-postgresql-credentials
