externalTcpProxy:
  clusterDomain: seang.shop
  kubeClusterDomain: benzcluster
  expose:
    mongodb: true
  ports:
    mongodb: 27017

mongodb:
  enabled: true
  credentials:
    clusterAdminUser: clusterAdmin
    clusterAdminPassword: "Admin@1234"
    userAdminUser: userAdmin
    userAdminPassword: "Admin@1234"
    clusterMonitorUser: clusterMonitor
    clusterMonitorPassword: "Admin@1234"
    databaseAdminUser: databaseAdmin
    databaseAdminPassword: "Admin@1234"
    backupUser: backup
    backupPassword: "Admin@1234"
    replicationKey: "replicationKey1234"
  cluster:
    instances: 3
    resources:
      requests:
        cpu: "200m"
        memory: "512Mi"
      limits:
        cpu: "500m"
        memory: "1Gi"
  storage:
    size: 10Gi
    storageClass: longhorn

postgresql:
  enabled: false
mysql:
  enabled: false
redis:
  enabled: false
cassandra:
  enabled: false