apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: wave-69ddeb6f-tcp
  namespace: ns-porkeat-c18c6214
spec:
  entryPoints:
  - postgresql
  routes:
  - match: 'HostSNI(`wave.seang.shop`) '
    services:
    - name: wave-69ddeb6f-postgresql-rw
      port: null
  tls:
    passthrough: true
