global:
  clusterIdentity: wave-69ddeb6f
  vault:
    enabled: false
  externalSecrets:
    enabled: false
gateway:
  enabled: true
externalTcpProxy:
  enabled: false
postgresql:
  enabled: true
  externalAccess:
    enabled: true
    publicHostnames:
    - wave.seang.shop
  tls:
    enabled: true
    mode: operator
  cluster:
    bootstrap:
      database: aeg
      owner: app_wave
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1Gi
  storage:
    size: 10Gi
  credentials:
    admin: aweg
    superuser: aweg
