global:
  clusterIdentity: aefawe-3bcf75d3
gateway:
  enabled: true
externalTcpProxy:
  enabled: false
postgresql:
  enabled: true
  externalAccess:
    enabled: true
    publicHostnames:
    - aefawe.seang.shop
  tls:
    enabled: true
    mode: operator
  cluster:
    bootstrap:
      database: aefae
      owner: app_aefawe
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1Gi
  storage:
    size: 10Gi
  credentials:
    admin: aef
    superuser: aef
