apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: postgresijqowx-tcp
  namespace: ns-pengseangsim210-gmail-com-9d7d574c
spec:
  entryPoints:
  - postgresql
  routes:
  - match: HostSNI(`postgrest.seang.shop`)
    services:
    - name: postgresijqowx-postgresql-rw
      port: 5432
  tls:
    passthrough: true
