global:
  clusterIdentity: adfea-6bd8151d
  vault:
    enabled: false
  externalSecrets:
    enabled: false
gateway:
  enabled: true
externalTcpProxy:
  enabled: false
  expose:
    postgresql: true
    mongodb: false
    mysql: false
    redis: false
    cassandra: false
  ports:
    postgresql: 15435
postgresql:
  enabled: true
  externalAccess:
    enabled: true
    publicHostnames:
    - adfea.seang.shop
  tls:
    enabled: true
    mode: operator
  cluster:
    bootstrap:
      database: egwrg
      owner: app_adfea
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1Gi
  storage:
    size: 10Gi
  credentials:
    admin: wergr
    superuser: wergr
