global:
  clusterIdentity: demos
  backupBucket: a8s-clusterdb-backup
gateway:
  enabled: true
postgresql:
  enabled: true
  externalAccess:
    publicHostnames:
    - demos.seang.shop
  cluster:
    imageName: ghcr.io/cloudnative-pg/postgresql:16.14
    instances: 3
    bootstrap:
      database: demosdb
      owner: app_demos
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi
  storage:
    size: 4Gi
    wal:
      enabled: false
  pooler:
    enabled: true
  externalSecretRef: demos-postgresql-app
  superuserExternalSecretRef: demos-postgresql-credentials
