global:
  clusterIdentity: project-2814ee42
externalTcpProxy:
  expose:
    postgresql: true
    mongodb: false
    mysql: false
    redis: false
    cassandra: false
  ports:
    postgresql: 15436
postgresql:
  enabled: true
  externalAccess:
    enabled: true
    publicHostnames:
    - project.seang.shop
  tls:
    enabled: true
    mode: operator
  cluster:
    bootstrap:
      database: appdb
      owner: app_project
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1Gi
  storage:
    size: 10Gi
  credentials:
    superuser: '123463'
    admin: '123463'
