global:
  clusterIdentity: asdf-4ef70078
externalTcpProxy:
  ports:
    postgresql: 5432
postgresql:
  enabled: true
  cluster:
    bootstrap:
      database: asd
      owner: app_asdf
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1Gi
  storage:
    size: 10Gi
  credentials:
    admin: asdf
    superuser: asdf
