apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: asdf-07687f22-tcp
  namespace: ns-porkeat-c18c6214
spec:
  entryPoints:
  - postgresql
  routes:
  - match: 'HostSNI(`asdf.seang.shop`) '
    services:
    - name: asdf-07687f22-postgresql-rw
      port: null
  tls:
    passthrough: true
