global:
  clusterIdentity: seang-postgre-5ac630a2
postgresql:
  enabled: true
  externalAccess:
    enabled: true
    publicHostnames:
    - postgres-db.seang.shop
  cluster:
    instances: 2
    bootstrap:
      database: appdb
      owner: appuser
  credentials:
    admin: PostgresStrongPassword123!
    superuser: PostgresStrongPassword123!
  backup:
    enabled: true
    s3Credentials:
      accessKeyId:
        secretName: minio-credentials-seang-postgre-5ac630a2
        key: root-user
      secretAccessKey:
        secretName: minio-credentials-seang-postgre-5ac630a2
        key: root-password
    schedule:
      immediate: false
      cron: 0 0 2 * * *
