global:
  clusterIdentity: seang-postgre-ac2b2589
postgresql:
  enabled: true
  externalAccess:
    enabled: true
    publicHostnames:
    - postgres-db.seang.shop
  cluster:
    bootstrap:
      database: appdb
      owner: appuser
  credentials:
    superuser: PostgresStrongPassword123!
    admin: PostgresStrongPassword123!
  backup:
    enabled: true
    s3Credentials:
      accessKeyId:
        secretName: minio-credentials-db-seang-postgres
        key: root-user
      secretAccessKey:
        secretName: minio-credentials-db-seang-postgres
        key: root-password
    schedule:
      immediate: false
      cron: 0 0 2 * * *
