global:
  clusterIdentity: test-a81d9b80
postgresql:
  enabled: true
  externalAccess:
    enabled: true
    publicHostnames:
    - test.seang.shop
  tls:
    enabled: true
    mode: operator
  cluster:
    bootstrap:
      database: test
      owner: app_test
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1Gi
  storage:
    size: 10Gi
  credentials:
    superuser: test
    admin: test
