global:
  clusterIdentity: java
  backupBucket: a8s-clusterdb-backup
gateway:
  enabled: true
postgresql:
  enabled: true
  externalAccess:
    publicHostnames:
    - java.seang.shop
  cluster:
    imageName: ghcr.io/cloudnative-pg/postgresql:17.10
    instances: 3
    bootstrap:
      database: mydb
      owner: app_java
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi
  storage:
    size: 4Gi
    wal:
      enabled: false
  pooler:
    enabled: true
  externalSecretRef: java-postgresql-app
  superuserExternalSecretRef: java-postgresql-credentials
