global:
  clusterIdentity: seang-postgre-4aada1ea
postgresql:
  enabled: true
  externalAccess:
    enabled: true
    publicHostnames:
    - postgres-db.seang.shop
  tls:
    enabled: true
    mode: operator
  cluster:
    instances: 1
    bootstrap:
      database: appdb
      owner: appuser
  credentials:
    admin: PostgresStrongPassword123!
    superuser: PostgresStrongPassword123!
  backup:
    enabled: true
    s3Credentials:
      accessKeyId:
        key: root-user
        secretName: minio-credentials-seang-postgre-4aada1ea
      secretAccessKey:
        key: root-password
        secretName: minio-credentials-seang-postgre-4aada1ea
    schedule:
      immediate: false
      cron: 0 0 2 * * *
