global:
  clusterIdentity: mysql
gateway:
  enabled: true
mysql:
  enabled: true
  externalAccess:
    publicHostnames:
    - mysql.seang.shop
  storage:
    size: 4Gi
  haproxy:
    size: 2
  cluster:
    image: percona/percona-xtradb-cluster:8.0
    instances: 3
    resources:
      requests:
        cpu: 250m
        memory: 768Mi
      limits:
        cpu: 600m
        memory: 1536Mi
  externalSecretRef: mysql-mysql-credentials
