global:
  clusterIdentity: alex-62158316
  vault:
    enabled: false
  externalSecrets:
    enabled: false
gateway:
  enabled: true
externalTcpProxy:
  enabled: false
  expose:
    postgresql: true
    mongodb: false
    mysql: false
    redis: false
    cassandra: false
  ports:
    postgresql: 15434
postgresql:
  enabled: true
  externalAccess:
    enabled: true
    publicHostnames:
    - alex.seang.shop
  tls:
    enabled: true
    mode: operator
  cluster:
    bootstrap:
      database: aegae
      owner: app_alex
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1Gi
  storage:
    size: 10Gi
  credentials:
    admin: aefae
    superuser: aefae
