global:
  clusterIdentity: dara
gateway:
  enabled: true
postgresql:
  enabled: true
  externalAccess:
    publicHostnames:
    - dara.seang.shop
  cluster:
    instances: 3
    bootstrap:
      database: database
      owner: app_dara
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi
  storage:
    size: 4Gi
    wal:
      enabled: false
  pooler:
    enabled: true
  externalSecretRef: dara-postgresql-app
  superuserExternalSecretRef: dara-postgresql-credentials
