global:
  clusterIdentity: seang-cassand-d359f2be
cassandra:
  enabled: true
  externalAccess:
    enabled: true
    publicHostnames:
    - cassandra-db.seang.shop
  tls:
    enabled: true
    clientEncryption: true
  cluster:
    config:
      clusterName: seang-cassandra
      datacenter: dc1
  credentials:
    password: CassandraStrongPassword123!
  backup:
    enabled: true
    schedule:
      cron: 30 3 * * *
