apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: abc32-tcp
  namespace: ns-porkeat-c18c6214
spec:
  entryPoints:
  - postgresql
  routes:
  - match: HostSNI(`abc32.seang.shop`)
    services:
    - name: abc32-postgresql-pooler-rw
      port: 5432
  tls:
    passthrough: true
