global:
  clusterIdentity: abc32
  backupBucket: a8s-clusterdb-backup
gateway:
  enabled: true
postgresql:
  enabled: true
  externalAccess:
    publicHostnames:
    - abc32.seang.shop
  cluster:
    imageName: ghcr.io/cloudnative-pg/postgresql:18.4
    instances: 3
    bootstrap:
      database: abc
      owner: app_abc32
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi
  storage:
    size: 4Gi
    wal:
      enabled: false
  pooler:
    enabled: true
  externalSecretRef: abc32-postgresql-app
  superuserExternalSecretRef: abc32-postgresql-credentials
