global:
  clusterIdentity: abc-1cbe4318
postgresql:
  enabled: true
  externalAccess:
    enabled: true
    publicHostnames:
    - abc.seang.shop
  tls:
    enabled: true
    mode: operator
  cluster:
    bootstrap:
      database: abc
      owner: abc
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1Gi
  storage:
    size: 10Gi
  credentials:
    superuser: abc
    admin: abc
