global:
  clusterIdentity: postgrest-data
gateway:
  enabled: true
postgresql:
  enabled: true
  externalAccess:
    enabled: true
    publicHostnames:
    - postgrest-database-cluster.cluster-db.autonomous-istad.com
  tls:
    enabled: true
    mode: operator
  cluster:
    bootstrap:
      database: postgres
      owner: app_postgrest_database_cluster
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1Gi
  storage:
    size: 5Gi
  pooler:
    enabled: true
  externalSecretRef: postgrest-data-postgresql-app
  superuserExternalSecretRef: postgrest-data-postgresql-credentials
