global:
  clusterIdentity: postgres5cct9w
gateway:
  enabled: true
postgresql:
  enabled: true
  externalAccess:
    enabled: true
    publicHostnames:
    - seang-clone.seang.shop
  tls:
    enabled: true
    mode: operator
  cluster:
    imageName: ghcr.io/cloudnative-pg/postgresql:18
    bootstrap:
      database: database
      owner: app_seang
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi
  storage:
    size: 4Gi
  pooler:
    enabled: true
  externalSecretRef: postgres5cct9w-postgresql-app
  superuserExternalSecretRef: postgres5cct9w-postgresql-credentials
