# root-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationRoot
metadata:
  name: root-db-clusters
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/seang454/db-cluster-gitops.git
    targetRevision: master
    path: argocd/applicationsets    # ← folder where you store your ApplicationSet yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true