global:
  clusterIdentity: abc2a
  backupBucket: a8s-clusterdb-backup
gateway:
  enabled: true
postgresql:
  enabled: true
  externalAccess:
    publicHostnames:
    - abc2a.seang.shop
  cluster:
    imageName: ghcr.io/cloudnative-pg/postgresql:18.4
    instances: 3
    bootstrap:
      database: abc
      owner: app_abc2a
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi
  storage:
    size: 4Gi
    wal:
      enabled: false
  pooler:
    enabled: true
  externalSecretRef: abc2a-postgresql-app
  superuserExternalSecretRef: abc2a-postgresql-credentials
