global:
  clusterIdentity: postgresxkvkf7
gateway:
  enabled: true
postgresql:
  enabled: true
  externalAccess:
    enabled: true
    publicHostnames:
    - postgres-db.seang.shop
  tls:
    enabled: true
    mode: operator
  cluster:
    bootstrap:
      database: postgres
      owner: app_my_postgres
    resources:
      requests:
        cpu: 250m
        memory: 768Mi
      limits:
        cpu: 750m
        memory: 2Gi
  storage:
    size: 4Gi
  externalSecretRef: postgresxkvkf7-postgresql-app
  superuserExternalSecretRef: postgresxkvkf7-postgresql-credentials
