global:
  clusterIdentity: seang-redis-04c47d60
redis:
  enabled: true
  externalAccess:
    enabled: true
    publicHostnames:
    - redis-db.seang.shop
  auth:
    password: RedisStrongPassword123!
