global:
  clusterIdentity: test-9cb05183
externalTcpProxy:
  ports:
    postgresql: 5432
postgresql:
  enabled: true
  cluster:
    bootstrap:
      database: test
      owner: app_test
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1Gi
  storage:
    size: 10Gi
  credentials:
    superuser: test
    admin: test
