global:
  clusterIdentity: ae-704163e8
  vault:
    enabled: false
  externalSecrets:
    enabled: false
gateway:
  enabled: true
externalTcpProxy:
  enabled: false
postgresql:
  enabled: true
  externalAccess:
    enabled: true
    publicHostnames:
    - ae.seang.shop
  tls:
    enabled: true
    mode: operator
  cluster:
    bootstrap:
      database: fe
      owner: app_ae
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1Gi
  storage:
    size: 10Gi
  credentials:
    admin: egeg
    superuser: egeg
