global:
  clusterIdentity: seang-postgre-940ce473
externalTcpProxy:
  ports:
    postgresql: 15432
postgresql:
  enabled: true
  externalAccess:
    enabled: true
    publicHostnames:
    - postgres-db.seang.shop
  tls:
    enabled: true
    mode: operator
  connection:
    username: userdb
    password: postgres@1234
    port: 15432
  cluster:
    instances: 1
    bootstrap:
      database: Postgrestdb
      owner: userdb
  backup:
    enabled: true
    s3Credentials:
      accessKeyId:
        key: root-user
        secretName: minio-credentials-seang-postgre-940ce473
      secretAccessKey:
        key: root-password
        secretName: minio-credentials-seang-postgre-940ce473
    schedule:
      cron: 0 * 9 * * *
      timeZone: Asia/Phnom_Penh
      immediate: false
