apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: mydb-tcp
  namespace: ns-ericva014-gmail-com-58019f5a
spec:
  entryPoints:
  - postgresql
  routes:
  - match: HostSNI(`mydb.seang.shop`)
    services:
    - name: mydb-postgresql-pooler-rw
      port: 5432
  tls:
    passthrough: true
