global:
  clusterIdentity: aefw-7aef37ff
postgresql:
  enabled: true
  externalAccess:
    enabled: true
    publicHostnames:
    - aefw.seang.shop
  tls:
    enabled: true
    mode: operator
  cluster:
    bootstrap:
      database: aefwe
      owner: aef
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1Gi
  storage:
    size: 10Gi
  credentials:
    admin: afea
    superuser: afea
