global:
  clusterIdentity: wefae-2cb52bb7
postgresql:
  enabled: true
  externalAccess:
    enabled: true
    publicHostnames:
    - wefae.seang.shop
  tls:
    enabled: true
    mode: operator
  cluster:
    bootstrap:
      database: eafwef
      owner: app_wefae
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1Gi
  storage:
    size: 10Gi
  credentials:
    superuser: veawve
    admin: veawve
